# Generated by Django 3.2.6 on 2021-08-18 10:47

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_companyinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_company', froala_editor.fields.FroalaField()),
                ('vision_and_values', froala_editor.fields.FroalaField()),
                ('lead_structure', froala_editor.fields.FroalaField()),
                ('our_belief', froala_editor.fields.FroalaField()),
                ('customer_support', froala_editor.fields.FroalaField()),
                ('sustainability', froala_editor.fields.FroalaField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomerSatisfaction',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='located_at',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/product_images'),
        ),
    ]
