# Generated by Django 3.2.6 on 2021-08-18 11:33

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210818_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About_us'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact_us'},
        ),
        migrations.AddField(
            model_name='about_us',
            name='our_quality',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
