# Generated by Django 3.2.6 on 2021-08-22 18:07

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210819_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideBtnText', models.CharField(max_length=20)),
                ('slide1name', models.CharField(max_length=100)),
                ('slide1text', froala_editor.fields.FroalaField()),
                ('slide2name', models.CharField(max_length=100)),
                ('slide2text', froala_editor.fields.FroalaField()),
                ('slide3name', models.CharField(max_length=100)),
                ('slide3text', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
