# Generated by Django 3.2.6 on 2021-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210828_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='civility',
            field=models.CharField(choices=[('Mrs.', 'Mrs'), ('Mr.', 'Mr.'), ('Other', 'Other')], default='Mrs.', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position_to_hold',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Webmaster', 'Webmaster')], default='Webmaster', max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
    ]
