# Generated by Django 3.2.6 on 2021-08-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210830_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='DoB',
        ),
        migrations.AlterField(
            model_name='staff',
            name='civility',
            field=models.CharField(choices=[('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Other', 'Other')], default='Mrs.', max_length=15),
        ),
    ]
